### ISSUE TITLE
Using the point biserial correlation

### ISSUE THREAD

**Issue by mxkenclajenjul** [hyunsooseol/seolmatrix#2]
I cannot input a categorical dichotomous variable.
![image](https://user-images.githubusercontent.com/115337342/194691348-d1d4cfc1-0ed4-458e-845f-1391f77e0414.png)

**Comment by hyunsooseol** [comment]
Hi [mxkenclajenjul](https://github.com/mxkenclajenjul)

You can change measure type into continuous variable and input it.

Cheers
Seol

**Comment by hyunsooseol** [comment]
Hi [mxkenclajenjul](https://github.com/mxkenclajenjul)

Some problems happened in it. hmm. . . I will check it soon.

**Comment by hyunsooseol** [comment]
Hi [mxkenclajenjul](https://github.com/mxkenclajenjul)

Bug fixed and update from jamovi library now.

Cheers
Seol
