### ISSUE TITLE
Issue with ICC calcul

### ISSUE THREAD

**Issue by KevinLeToupin** [hyunsooseol/seolmatrix#3]
Hi,
When we try to calcul our interrater reliability and ICC, no results are appearing on screen. We only see a subtext under ''Rater reliability" and it says: "subscript out of bound". 

What does it means and can it be fixed?

Thank you!

**Comment by hyunsooseol** [comment]
Hi [KevinLeToupin](https://github.com/KevinLeToupin)

Could you attach a file as zip here ? I will take a look at.

Best
Seol
