### ISSUE TITLE
The seolmatrix jamovi module immediately reports a processing error

### ISSUE THREAD

**Issue by R180** [hyunsooseol/seolmatrix#4]
The seolmatrix jamovi module immediately reports a processing error: "_This analysis has terminated, likely due to hitting  resource limit._". (Windows 10; jamovi 2.3.24.)

![seolmatrixUntitled](https://user-images.githubusercontent.com/16230091/228056105-218efa27-62e0-4b32-b49b-cbb5265af55b.png)

**Comment by hyunsooseol** [comment]
Dear [R180](https://github.com/R180)

Try another computer to see same thing happens.

Best
Seol

**Comment by R180** [comment]
Thank you. It does work on a different computer. I'm finding that jamovi modulus sometimes do not work as intended when the OS has a lot of security in place.
