### ISSUE TITLE
Feature request: Krippendorff's alpha

### ISSUE THREAD

**Issue by evanmiltenburg** [hyunsooseol/seolmatrix#5]
I like this module for its ability to compute interrater reliability, with correlations and Fleiss Kappa. The only feature I am missing is Krippendorff's alpha. Would it be possible to add it? It's mostly similar to Fleiss Kappa, but there should be a dropdown menu to select the type of data: `"nominal","ordinal","interval","ratio"`

**Comment by hyunsooseol** [comment]
Dear [evanmiltenburg](https://github.com/evanmiltenburg)

It's available in jamovi library as shown below.
![image](https://user-images.githubusercontent.com/37318620/233811680-2db6fa50-a598-43c5-978b-4aa00d4aced0.png)

Best

**Comment by evanmiltenburg** [comment]
Thanks! I will check it out and report back :)

**Comment by evanmiltenburg** [comment]
It doesn't show up in Jamovi. When I search for the package it keeps showing 3.7.1. but not 3.7.2.

**Comment by hyunsooseol** [comment]
What OS are you using? It is showing on WIN 10 as shown below.

![image](https://user-images.githubusercontent.com/37318620/234129277-57dc5001-f833-47a1-b8d7-e2152fa61aa8.png)

**Comment by evanmiltenburg** [comment]
I'm using macOS. Here's a screenshot that I just took after uninstalling 3.7.1. and searching for the module again:
<img width="1392" alt="Screenshot 2023-04-25 at 09 34 03" src="https://user-images.githubusercontent.com/1513355/234206501-53bd2204-de38-4425-9635-dd930ba7c472.png">

Next I'll try reinstalling Jamovi.

**Comment by evanmiltenburg** [comment]
Did not work, but if it does on Windows then I think it is a Jamovi issue. I will notify them.

**Comment by jonathon-love** [comment]
looks like the library build process failed at some point, after the windows version was built, but before the macOS version.

i've triggered a rebuild. should be fixed in the next hour or so.

**Comment by evanmiltenburg** [comment]
I have good news and bad news. Good news: the module now shows up in Jamovi! The bad news: I'm not sure the values it computes are correct. I have attached a file that I tried in both JASP and Jamovi.

Here are the results from JASP:
<img width="1360" alt="Screenshot 2023-05-16 at 10 47 35" src="https://github.com/hyunsooseol/seolmatrix/assets/1513355/fe62c03f-97b0-40e7-8eb2-c0373bb16e72">

Here are the results from Jamovi with the `seolmatrix` module:
<img width="1392" alt="Screenshot 2023-05-16 at 10 48 08" src="https://github.com/hyunsooseol/seolmatrix/assets/1513355/d2689758-92e7-480f-9889-b426dcf4cf86">

As a sanity check I also computed the Kappa scores. These are all the same between both programs. But JASP gives an alpha score of 0.846, while Jamovi returns -0.424. Given the kappa scores, the former seems more likely than the latter. (I also purposefully made this file to show high agreement.)

[voorbeeld_hoge_agreement.ods](https://github.com/hyunsooseol/seolmatrix/files/11485843/voorbeeld_hoge_agreement.ods)

**Comment by hyunsooseol** [comment]
Hi [evanmiltenburg](https://github.com/evanmiltenburg)

Thanks for using seolmatrix. To compare the results that I used in jamovi with **irr** R package. please attach the .omv file that you used in here.

Best Regards
Seol

**Comment by hyunsooseol** [comment]
you can attach excel data file in here.

**Comment by evanmiltenburg** [comment]
It is linked at the bottom of this comment: https://github.com/hyunsooseol/seolmatrix/issues/5#issuecomment-1549261300

**Comment by hyunsooseol** [comment]
OK I will take a look. . .

**Comment by hyunsooseol** [comment]
![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/a15e6805-bcec-4b63-8a31-96c05f0a8fd2)

**Comment by hyunsooseol** [comment]
Hi [evanmiltenburg](https://github.com/evanmiltenburg)

The result in **irr** R package is consistent with the result in jamovi.

Best Regards
Seol

**Comment by evanmiltenburg** [comment]
Hi Seol,

Thanks for the quick responses.

The JASP developer [pointed out](https://github.com/jasp-stats/jasp-issues/issues/2140#issuecomment-1549519488) the issue here: Krippendorff's alpha assumes that raters are rows and items are columns, whereas kappa assumes that raters are columns and items are rows. 

One straightforward solution would be to implement a dropdown menu with default "Raters are columns" and optional "Raters are rows". These options would either transpose the rows (or not) for the computation of the alpha score. Code would be something like:

```
ex <- read.csv("example.csv")
ex <- as.matrix(ex)
kripp.alpha(t(ex), "ordinal") # Compute Krippendorff's alpha using transposed matrix.
```

Using the transposed matrix by default to compute Krippendorff's alpha makes sense because then the file is in line with the required format for the other scores. This also matches JASP's implementation, which is a plus in terms of consistency. Having a dropdown menu to toggle the transpose on or off means that users never have to transform their own data file.

Best wishes,
Emiel

**Comment by JuppStats** [comment]
Dear all,
thanks to [hyunsooseol](https://github.com/hyunsooseol) the above discussed option to create a dropdown menu with default "Raters are columns" and optional "Raters are rows" for Krippendorffs Alpha is now available in v3.8.1. 

Thanks for the incredible support!

**Comment by evanmiltenburg** [comment]
This is great! But I don't see 3.8.1. in Jamovi yet. The latest available version is 3.7.2.
I'm using Jamovi 2.3.28, which seems to be the latest version on macOS.

**Comment by hyunsooseol** [comment]
Hi [evanmiltenburg](https://github.com/evanmiltenburg)

you should update Jamovi first and then try to install the latest version of seolmatrix module.

Best Regards
Seol

**Comment by evanmiltenburg** [comment]
Thanks for your response. I'm using the latest *stable* version for macOS. So I guess Mac users either need to wait or use the latest (not stable) release? Alternatively the Jamovi website should be updated.

**Comment by hyunsooseol** [comment]
Hi 

You should use current version of MacOs shown below.
![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/fd625564-5a44-43e9-9b21-dd7f2fd7fe9a)

Cheers
Seol

**Comment by evanmiltenburg** [comment]
Yeah that's what I thought: not supported by the solid release yet. I've installed the current `2.4.8.0` release, but there's no `seolmatrix` version `3.8.1`, only `3.8.0`, which does not have the "raters are columns" feature.

**Comment by hyunsooseol** [comment]
Could you ask @jonathon-love  to see what happens on MacOS?

**Comment by evanmiltenburg** [comment]
Ah, it works now! It seems there was an update between my post and now. I guess this issue can be closed now 👍

**Comment by hyunsooseol** [comment]
Hi

You can update the module in jamovi library now.
![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/de041527-b435-4dc2-b268-b0d57be692de)

Best Regards
Seol
