### ISSUE TITLE
Fleiss Kappa: option "Raters are columns" and optional "Raters are rows" 

### ISSUE THREAD

**Issue by celiagconejo** [hyunsooseol/seolmatrix#6]
Hi!
I wanted to make a suggestion for doing content analysis. Fleiss's Kappa and Krippendorf alpha are two statistics that are calculated together.

Is it possible to add the option to change the raters to rows or columns in both statistics?

Thank you very much for the seolmatrix module
Best regards
Celia

**Comment by hyunsooseol** [comment]
Hi Celia

Thanks for your requests.

I will implement it in the next version. I will let you know when it's available in jamovi library.

Best Regards
Seol

**Comment by hyunsooseol** [comment]
Hi Celia

Could you update the module in jamovi library now?

![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/dfb32378-6431-4c42-8b01-68c736b2a606)

Best Regards
Seol

**Comment by celiagconejo** [comment]
Thank you so much Seol! I just update the module. 
Best Regards
Celia
