### ISSUE TITLE
'S' is not positive definite

### ISSUE THREAD

**Issue by snahgnuhc** [hyunsooseol/seolmatrix#7]
Hi there, thank you very much for creating this module.

I am facing this issue of 'S' is not positive definite when running the rater reliability analyses (ICC) for a sample of 10 cases, and 3 rater scores.

When running the same data in SPSS, the results seems to be able to generate w/o this error message.

Seeking enlightenment on what might be the issue please. thank you!

**Comment by snahgnuhc** [comment]
For context, the small sample (10 cases) was the training set for raters to align expectations before subsequent independent ratings of a larger sample.

**Comment by hyunsooseol** [comment]
Hi [snahgnuhc](https://github.com/snahgnuhc)

Could you attach a omv file that cause errors here?

Cheers
Seol

**Comment by snahgnuhc** [comment]
Hi @hyunsooseol please see the attached.

Thanks!

[Jamovi Sample Error Data (anon).zip](https://github.com/hyunsooseol/seolmatrix/files/13228799/Jamovi.Sample.Error.Data.anon.zip)

**Comment by hyunsooseol** [comment]
Hi Hi [snahgnuhc](https://github.com/snahgnuhc)

There was a problem building the graph, I am currently updating the module. It should be updated this week. I'll let you know when it is available.

Best Regards
Seol

**Comment by hyunsooseol** [comment]
Hi [snahgnuhc](https://github.com/snahgnuhc)

It's available in jamovi library. update it now.
![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/00c1389a-478a-4d52-b2ef-8e841b4d129e)

Best Regards
Seol

**Comment by snahgnuhc** [comment]
Thanks Seol!

I can't seem to find 3.8.2 though. On jamovi's website its, 3.6.2 and the native desktop library shows me 3.7.2.

Thanks!
Hans

**Comment by hyunsooseol** [comment]
Hi Hans

What OS are you using for jamovi? you should update latest version(current version) of jamovi and you will find the updated module in jamovi library, I think.

Best Regards
Seol

**Comment by snahgnuhc** [comment]
Thanks Seol, managed to get it once I updated. Was using 2.3.21 (solid).

Observed that it doesn't work on the latest solid release (2.3.28) but works on the current release (2.4.11)

Cheers!
Hans
