### ISSUE TITLE
일반화가능도이론

### ISSUE THREAD

**Issue by waurimal** [hyunsooseol/seolmatrix#8]
[writing.zip](https://github.com/hyunsooseol/seolmatrix/files/15055884/writing.zip)

**Comment by hyunsooseol** [comment]
안녕하세요. 

다음 formula를 명세화 해주셔야 합니다.
![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/dfcd592d-9559-4034-8b65-8f2e3a751f5a)

그리고 자세한 사항은 gtheory R 패키지를 참조 하시면 될것 같습니다.
참고로 정상적으로 작동하는 파일을 첨부 해드립니다.
[Efdata.zip](https://github.com/hyunsooseol/seolmatrix/files/15056197/Efdata.zip)

**Comment by waurimal** [comment]
고맙습니다. 교수님.  formula에 정확하게 써줘야 하는군요.

**Comment by waurimal** [comment]
교수님, 잘 됩니다. 혹시 D study plot을 그릴 때 facet의 수 범위 지정도 가능하면 더 좋을 것 같습니다. 예를 들면, 4~10

**Comment by hyunsooseol** [comment]
옵션에 있습니다. ^^

![image](https://github.com/hyunsooseol/seolmatrix/assets/37318620/9f50c733-5d4e-4a62-8b9b-31051ed1835f)
